### ISSUE TITLE
`sls webpack serve` does not pass POST data to event.body

### ISSUE THREAD

**Issue by fwang** [elastic-coders/serverless-webpack#121]
**Steps to reproduce**
1. run `sls webpack serve`
2. curl http://localhost:8000/hello -d "hello world"
3. event.body is { }

**Lambda function**
```
export const hello = async (event, context, callback) => {
  const response = {
    statusCode: 200,
    body: event.body
  };

  callback(null, response);
};
```

**Serverless.yml**
```
...
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
```
