### ISSUE TITLE
Dependencies from package.json are not loaded into .zip package

### ISSUE THREAD

**Issue by wenderjean** [elastic-coders/serverless-webpack#169]
Hey guys, I am fighting with a problem and I'm not sure if It's exactly a `bug`.
I have the following `package.json`

```
{
  "dependencies": {
    "aws-sdk": "^2.86.0",
    "lodash": "^4.17.4",
    "joi": "^10.2.0",
    "structure": "^1.2.0"
  },
  "devDependencies": { ... }
}
```

My `serverless.yml` is like:

```
service: my-service

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10

functions:
  ...
```

My problem is when I try to deploy my functions to `AWS`, the `structure` dependency is not recognized there, I got the error `module not found`, when I look to the zip generated by serverless package I can see that's really does not exists my dependency there, inside `node_modules`.

any  tip?
