### ISSUE TITLE
No matching handler found for 'handler'. Check your service definition

### ISSUE THREAD

**Issue by vcarel** [elastic-coders/serverless-webpack#171]
I just upgraded from serverless-webpack 2.0.0 to 2.2.0 and got the following error. It was working perfectly with the previous version.

    No matching handler found for 'handler'. Check your service definition

Is there anything wrong in my configuration?

```
service: my_service

provider:
  ...

custom:
  webpack: webpack.config.serverless.js

functions:
  my_function:
    handler: handler.my_function
    events:
       ...

plugins:
  - serverless-webpack
```

FYI I'm on serverless latest (as of today: 1.18.1)

**Comment by HyperBrain** [comment]
Where is your handler.js located? In the service root directory?

**Comment by vcarel** [comment]
It's defined in my webpack configuration:

```
module.exports = {
  entry: ['./src/server/handler.js'],
```

**Comment by vcarel** [comment]
By the way, I'm using yarn to freeze dependencies. I noticed while trying several configurations that I can get the issue with 2.0.0 too. It looks like the problem appears with the upgrade of an inner dependency, somewhere.

**Comment by HyperBrain** [comment]
Ok. I think that's the problem. The function definition should define the path - otherwise you'd also get issues with other plugins that need to find the handler. The problem is, that Serverless (the framework) is completely unaware of the handler location in your case.

So, please change the handler definition in your serverless.yml.

... and the good thing:
With 2.2.0 you now do not have to set the entries manually anymore in your webpack config. Just use:
```
// webpack.conf.js
const slsw = require('serverless-webpack');
module.exports = {
  entry: slsw.lib.entries
};
```
Then you can add functions to your service without changing the config again.

**Comment by HyperBrain** [comment]
This is the function definition you should set:
```
functions:
  my_function:
    handler: src/server/handler.my_function
```

**Comment by vcarel** [comment]
I was searching how to define the path. I didn't put the serverless.yml is the same directory as the handler file, and that does not help.

Well, following what you said, I get another error:

  Type Error ---------------------------------------------
 
  Path must be a string. Received { 'src/server/handler': './src/server/handler.js' }

with

```
functions:
  my_function:
    handler: 'src/server/handler.my_function'
```

**Comment by vcarel** [comment]
Ok, found. The problem is that `slsw.lib.entries` does not contain an array, but the object
`{ 'src/server/handler': './src/server/handler.js' }`

If I just use the previous config, it works fine
```
module.exports = {
  entry: ['./src/server/handler.js']
```

So, at the end, the fix was to set the path in the handler definition:
```
functions:
  my_function:
    handler: src/server/handler.my_function
```

**Comment by HyperBrain** [comment]
Glad to hear that it now works 👍

**Comment by lewisblackwood** [comment]
Hey 👋 Apologies to reopen this, but I'm also seeing the same issue.

I'm trying to upgrade the [`serverless-babel-starter`](https://github.com/postlight/serverless-babel-starter) repo to use `2.2.0`.

When I try to deploy, I get the error message:

`Path must be a string. Received { 'src/handler': './src/handler.js' }`

I've updated the `webpack.config.js` to:

```javascript
const nodeExternals = require('webpack-node-externals');
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  externals: [nodeExternals()],
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['babel'],
      include: __dirname,
      exclude: /node_modules/,
    }],
  },
};
```

and the `serverless.yml` to:

```yml
functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
      # Ping every 5 minutes to avoid cold starts
      - schedule:
          rate: rate(5 minutes)
          enabled: true
```

Do you have any suggestions? Would be great to get `2.2.0` working to be able to deploy a single function at a time.
