### ISSUE TITLE
support multiple webpack config files

### ISSUE THREAD

**Issue by mikestaub** [elastic-coders/serverless-webpack#19]
Currently this plugin only supports one webpack config file that is used during local development and during ```serverless deploy```.

I would like to have two different webpack configurations, one for each of those scenarios.

These could be specified in serverless.yml like so:

```
custom:
  webpack: 
    dev: ./webpack.dev.config.js
    deploy: ./webpack.deploy.config.js
```

The default behavior would still apply: if either was not specified, 'webpack.config.js' will be used.

What do you think?

**Comment by mikestaub** [comment]
Currently, I'm setting an environment variable locally and checking for that in my webpack.config.js file. I used that to determine which config to use. Perhaps this is actually the correct way to solve this, I'm not sure.

**Comment by andymac4182** [comment]
@mikestaub I am currently doing this at the moment for this in my project.
`serverless.yml`
```
custom:
  webpack: ${webpackConfigFile}
```

`serverless.env.yml`
```
vars:
  webpackConfigFile: webpack.local.config.js
stages:
  prod:
    vars: 
      webpackConfigFile: webpack.octopus.config.js
```

hope this helps
