### ISSUE TITLE
V3: Bundled dependancies - module initialization error - no read access

### ISSUE THREAD

**Issue by amitaymolko** [elastic-coders/serverless-webpack#190]
I'm having an issue with certain dependancies not having read access and that causes errors on deployed lambda.
Error:
```
module initialization error: Error
at Error (native)
at Object.fs.openSync (fs.js:641:18)
at Object.fs.readFileSync (fs.js:509:33)
at Object.Module._extensions..js (module.js:578:20)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/node_modules/rest-facade/src/index.js:2:11)
```
locally when installing with npm the `rest-facade` module has the correct permissions for all files in `/src` when its packaged with the plugin it doesn't:

packaged `/node_modules/rest-facade/src/`:
```
13799175 -rw-------  1 amitay  admin  9993 Dec 31  1979 Client.js
13799176 -rw-------  1 amitay  admin   207 Dec 31  1979 defaultOptions.js
13799177 drwxr-xr-x  2 amitay  admin   170 Aug 16 11:45 exceptions
13799181 -rw-r--r--  1 amitay  admin   154 Dec 31  1979 index.js
13799182 -rw-------  1 amitay  admin    38 Dec 31  1979 mocha.opts
13799183 -rw-------  1 amitay  admin   389 Dec 31  1979 utils.js
```
project `/node_modules/rest-facade/src/`:
```
12991081 -rw-r--r--  1 amitay  admin  9993 Oct 19  2016 Client.js
12991079 -rw-r--r--  1 amitay  admin   207 Oct 19  2016 defaultOptions.js
12980542 drwxr-xr-x  2 amitay  admin   170 Aug 13 17:44 exceptions
12991080 -rw-r--r--  1 amitay  admin   154 Mar 28 18:30 index.js
12991084 -rw-r--r--  1 amitay  admin    38 Oct 19  2016 mocha.opts
12991083 -rw-r--r--  1 amitay  admin   389 Oct 19  2016 utils.js
```

using:
`webpack: ^3.5.4`
`serverless-webpack: ^3.0.0-rc.1`
`serverless: 1.19.0`

`webpack.config.js`:
```
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
    entry: slsw.lib.entries,
    target: 'node',
    externals: [nodeExternals({
        modulesFromFile: true
    })],
    module: {
        rules: [
            {
                test: /\.jql$/,
                exclude: /node_modules/,
                use: ['jql-loader', 'babel-loader']
            },
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                use: ['shebang-loader', 'babel-loader']
            },
            {
                test: /\.json$/,
                use: ['json-loader']
            }
        ]
    },
    output: {
        libraryTarget: 'commonjs',
        path: path.join(__dirname, '.webpack'),
        filename: '[name].js'
    }
};
```

`serverless.yml`:
```
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline-scheduler
  - serverless-offline
  - serverless-mocha-plugin
  - api-docs // custom plugin

package:
  include:
    - node_modules/**
    - yarn.lock
  exclude:
    - .git
    - .requirements
    - .ses-mailbox
    - apidoc.json
    - apidoc_shared.js
    - docs
    - cfn_lambda_helpers
    - seed
    - test
  individually: true
```
