### ISSUE TITLE
Cannot POST to local simulated API Gateway ?

### ISSUE THREAD

**Issue by StefH** [elastic-coders/serverless-webpack#27]
I've executed this command:
```
serverless webpack serve
```

Output is like:
```
c:\my-folder>serverless webpack serve
Serverless: Serving functions...
ts-loader: Using typescript@2.0.0 and c:\my-folder\tsconfig.json
``` 

However when using Postman to post to `http://localhost:8000` with correct Accept and Content-Type, I get an error in Postman:

```
Cannot POST /
```

I checked that it's listening to port 8000 on my sytstem.

**Comment by thenikso** [comment]
Have you added something like this to your `serverless.yml`?

```yaml
functions:
  yourFunction:
    handler: handler.yourFunciton
    events:
      - http:
          method: post
          path: myPath
```
