### ISSUE TITLE
Shorthand http event syntax throws "Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by marcuswhybrow** [elastic-coders/serverless-webpack#44]
`serverless-webpack` `1.0.0-rc.2` at [this line](https://github.com/elastic-coders/serverless-webpack/blob/v1.0.0-rc.2/lib/serve.js#L44) assumes a serverless.yml event format like this:

``` yml
functions:
  myfunction:
    handler: handlers.myfunction
    events:
      - http:
          method: POST       # method and path are
          path: myfunction   # defined as separate keys
```

However using the http event string shorthand...

``` yml
functions:
  myfunction:
    handler: handlers.myfunction
    events:
      - http: POST myfunction

```

...throws the error...

```
Cannot read property 'toLowerCase' of undefined
... serverless-webpack/lib/serve.js:45:40 ...
```
