### ISSUE TITLE
Strange behavior with Mongoose

### ISSUE THREAD

**Issue by mrpatiwi** [elastic-coders/serverless-webpack#70]
Trying mongoose with `context.callbackWaitsForEmptyEventLoop = false` so the function should end after calling `callback(...)` works different while using `serverless-webpack` as a plugin and when manually packing the project with webpack.

```js
// webpack.config.js
module.exports = {
  entry: './handler.js',
  target: 'node',
  output: {
    libraryTarget: 'commonjs',
    path: 'dist',
    filename: 'handler.js',
  },

  // Any module with native extensions has to be excluded
  externals: [
    'mongoose',
  ],
}
```

```js
// handler.js
'use strict';
import mongoose from 'mongoose';
import Promise from 'bluebird';

export const UserSchema = new mongoose.Schema({
  name: String,
});
const User = mongoose.model('User', UserSchema);

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost/lambda';
mongoose.connect(MONGO_URI);

module.exports.handler = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false
  return User.find({})
    .then(results => callback(null, results))
    .catch(callback);
};
```

## With `serverless-webpack`

```yml
# serverless.yml
service: users

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

functions:
  index:
    handler: handler.handler
    events:
      - http:
          path: users
          method: get
```

When calling the function it gets stuck on some event-loop and eventually it times-out on AWS.

## Without `serverless-webpack`

```yml
# serverless.yml
service: users

package:
  include:
    - dist/**

functions:
  index:
    handler: dist/handler.handler
    events:
      - http:
          path: users
          method: get
```

Manually running `webpack` and:

```sh
cd dist 
echo "{}" > package.json 
npm i --save mongoose
cd ..
```

And then running it locally or on production it work as expected.
