### ISSUE TITLE
rc.2 -> rc.3 fails

### ISSUE THREAD

**Issue by bebbi** [elastic-coders/serverless-webpack#79]
When checking for #67 status, and only replacing rc.2 -> rc.3, and no further changes, the service doesn't work on `serverless webpack serve` anymore.

First, it logs a new `core undefined` message

```
Serverless: Serving functions...
  POST - http://localhost:8000//myEndpoint
core undefined
```

then runs. It appears that the code fully works and then fails when returning a response.

```
RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:558:10)
    at ServerResponse.send (/mypath/node_modules/express/lib/response.js:205:10)
    at func (/mypath/node_modules/serverless-webpack/lib/serve.js:125:39)
    at /mypath/.webpack/handler.js:108:6
    at run (/mypath/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /mypath/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/mypath/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

(Used serverless 1.4.0 for both). Endpoint config if relevant:
```
events:
  - http:
      path: /myEndpoint
      method: post
      cors: true
      integration: Lambda
      request:
        passThrough: NEVER
      response:
        headers:
          Content-Type: "'application/json'"
```
