### ISSUE TITLE
Some, not all, environment vars are missing

### ISSUE THREAD

**Issue by bebbi** [elastic-coders/serverless-webpack#99]
Environment variables are not all available to functions. Only the variables defined globally and those for the first function will be available when running locally. Example:

`serverless.yml`:

```
provider:
  environment:
    A: 'A'
functions:
  func1:
    environment:
      F1: '1'
  func2:
    environment:
      F2: '2'
```

In this setup, the only variables available to the local environment are `A` and `F1`.
If I move func2 on top of func1, it is however `A` and `F2`.
